version: '3.8'
services:
  dashboard:
    image: thisisnotadrilldash:latest
    build:
      context: ./packages/dashboard
      args:
        VITE_CLERK_PUBLISHABLE_KEY: ${VITE_CLERK_PUBLISHABLE_KEY}
        VITE_API_TARGET: ${VITE_API_TARGET}
    ports:
      - "80:80"
    env_file:
      - ./packages/dashboard/.env
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - VITE_API_TARGET=http://api:8080
    depends_on:
      - api
      # These are just for debugging if container problems arise
#    stdin_open: true
#    tty: true
#    command: ["/bin/sh"]

  api:
    image: thisisnotadrillapi:latest
    build:
      context: ./packages/api
    ports:
      - "8080:8080"
    env_file:
      - ./packages/api/.env
    environment:
      - NODE_ENV=production
      - HOST=localhost
      - INBOUND_PORT=80
      - PROTOCOL=http
    extra_hosts:
      # Access to local postgres
      - "host.docker.internal:172.17.0.1"
