import React, { useEffect, useState, useRef } from 'react';
import { Navigate } from 'react-router-dom';
import { IconCopy, IconCheck } from '@tabler/icons-react';
import { useUser } from "@clerk/clerk-react";
import { ActionIcon, Anchor, Code, CopyButton, Group, Stack, Skeleton, 
         Image, Button, Paper, rem, Space, Text, TextInput, Title, Tooltip } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import { useAPIKeys } from './APIKeysContext';
import { useDateFormatters } from '../../lib/DateFormattersProvider';
import { useConfig } from '../../lib/ConfigContext';
import sdk, { ProjectFiles } from '@stackblitz/sdk';

import LogoComponent from '../Layout/LogoComponent';
import Navbar from '../Layout/Navbar';
import UserAuthentication from '../Layout/UserAuthentication';
import introClasses from './css/IntroPages.module.css';
import logoClasses from '../Layout/css/MainLayout.module.css';
import apiKeyClasses from './css/APIKeys.module.css';

interface FilesObject {
  files: {
    [key:string] : string;
  }
};

const PlaygroundComponent = () => {
  const { isSignedIn,user } = useUser();
  const { createAPIKey, fetchAPIKeys, playgroundAPIKeys } = useAPIKeys();
  const { pastTense, formatDisplayDate, formatDisplayTime } = useDateFormatters();
  const { apiBaseUrl, getBearerHeader } = useConfig();
  const [ repoFiles, setRepoFiles ] = useState<ProjectFiles>({});

  if (!isSignedIn) {
    return <Navigate to="/login" replace />;
  }
    
  const [opened, { toggle }] = useDisclosure();
  const temporaryAPIKeyValue = useRef<string | null>(null);
  const [ temporaryAPIKeyExpiration,  setTemporaryAPIKeyExpiration ] = useState('');

  const createTemporaryKey = async () => {
    if (!isSignedIn) {
      return; // can't do it if you ain't signed in
    }
    await createAPIKey('development', user.id, true);
    await fetchAPIKeys(user.id);
  }

  const fetchExampleRepo = async () => {
    let filesObj:FilesObject = {
      files: {}
    };
    if (user) {

      // Check if a valid API key exists. If not generate one.
      const expiresAt = playgroundAPIKeys[0]?.expiresAt?.toISOString();
      const isPast = (expiresAt ? pastTense(expiresAt) : false);

      if (playgroundAPIKeys.length > 0) {
        if (expiresAt && isPast) {
            //if (temporaryAPIKeyValue.current === null || isPast) {
            // If no valid key, generate a new one
            console.log('Generating temporary key because latest one is expired.');
            await createTemporaryKey();
          }
      } else {
        console.log('Generating temporary key because none exist yet.');
        await createTemporaryKey();
      }       

      const repoUrl = 'https://github.com/willkessler/this-is-not-a-drill-basic-example';
      try {
        const clerkId = user.id;
        const APIUrl = `${apiBaseUrl}/playground/fetch-example-app`;
        const response = await fetch(APIUrl, {
          method: 'POST',
          credentials: 'include',
          headers: await getBearerHeader({ 'Content-Type': 'application/json' }),
          body: JSON.stringify({
            clerkId, 
            repoUrl
          })
        });
        if (!response.ok) {
          throw new Error (`HTTP error! status: ${response.status}`);
        } else {
          console.log('Fetched repo contents from Tinad API.');                  
        }
        
        console.log('inside fetchExampleRepo');
        filesObj = await response.json();

      } catch (error) {
        console.error(`Error fetching repo, url: ( ${repoUrl} ).`, error);
        return null;
      }
    }

    // Inject a .env file using the current api key and other props into the file structure.
    // Since we cannot use import.meta.env (e.g. in stackBlitz), this file
    // is used to create "environment variables" on the fly.

    // this version is for the old react-based sample bank app
//  const envFileContents = `
// // Autogenerated values
//export const envConfig = {
//  TINAD_IMAGE_LOCATION:           'https://raw.githubusercontent.com/willkessler/this-is-not-a-drill-examples/main/public/',
//  TINAD_API_BASE_URL:             '${import.meta.env.VITE_TINAD_API_BASEURL}',
//  TINAD_ENDUSER_ID:               '${import.meta.env.VITE_TINAD_ENDUSER_ID}',
//  TINAD_API_KEY:                  '${temporaryAPIKeyValue.current}',
//  TINAD_IS_DEMO_SITE:             true,
//  TINAD_IS_STACKBLITZ_PLAYGROUND: true,
//};
//`;

//    filesObj.files['src/envConfig.ts'] = envFileContents;

//    filesObj.files['public/index.html'] = filesObj.files['index.html'];
//    filesObj.files['src/index.tsx'] = filesObj.files['src/main.tsx'];
//    // make module resolution to be a known value for stackblitz
//    filesObj.files['tsconfig.json'] = filesObj.files['tsconfig.json'].replace('bundler','nodenext');

    // insert the environment file into the repo
    const envFileContents = `
const environment = {
  API_KEY: '${temporaryAPIKeyValue.current}',
  API_ENDPOINT: '${import.meta.env.VITE_TINAD_API_BASEURL}',
};
export default environment;
`

    const repoPrefix = 'this-is-not-a-drill-basic-example-main';
    filesObj.files['environment.ts'] = envFileContents;
    filesObj.files['index.ts'] = filesObj.files[repoPrefix + '/src/index.ts'];
    filesObj.files['index.html'] = filesObj.files[repoPrefix + '/public/index.html'];
    filesObj.files['bundle.js'] = filesObj.files[repoPrefix + '/public/bundle.js'];

    console.log(filesObj.files);
    setRepoFiles(filesObj.files);
  }

/*
  const openStackblitz = async () => {
    await sdk.openGithubProject('willkessler/eznotifications', {
      openFile:'examples/react_sdk/src/App.tsx',
      newWindow: true,
      height:'90vh',
      showSidebar: true,
      view: 'both' as UIViewOption,
    });
  }
*/

  const gotoPlayground = async () => {
    // Now, we assume `temporaryAPIKeyValue.current` holds a valid API key (either existing or newly generated)
    try {
      // Copy the API key to the clipboard
      await navigator.clipboard.writeText(temporaryAPIKeyValue.current as unknown as string);
      console.log('API Key copied to clipboard');
    } catch (err) {
      console.error('Failed to copy API key to clipboard', err);
    }

    // Open the playground in codesandbox: doesn't work
    //https://codesandbox.io/p/devbox/github/willkessler/this-is-not-a-drill-examples?file=%2FREADME.md
    //    const codeSandboxUrl = 
    //          'https://codesandbox.io/p/sandbox/github/willkessler/this-is-not-a-drill-examples/main?file=README.md';
    //const stackblitzUrl = 
    // 'https://stackblitz.com/~/github.com/willkessler/this-is-not-a-drill-examples?apiKey=abc123';
    
    //window.open(stackblitzUrl, '_blank');
    //sdk.embedGithubProject('stackblitz', 'willkessler/this-is-not-a-drill-examples', {

    // this does work

    /* sdk.openGithubProject('willkessler/this-is-not-a-drill-examples', {
     *   newWindow: true,
     *   openFile: 'src/components/App.tsx',
     *   view: 'editor',
     *   height: 800,
     *   showSidebar: true,
     *   view: 'both'
     * }); */

    //console.log(`Files contains: ${JSON.stringify(repoFiles,null,2)}`);    
    //console.log(`tsconfig.json: ${repoFiles['tsconfig.json']}`);

    sdk.openProject(
      {
        title: 'This Is Not A Drill! Demo App',
        description: 'A simple app demonstrating how to use the TINAD React SDK.',
        files: repoFiles,
        template: 'typescript',
        dependencies: {
          "@this-is-not-a-drill/vanillajs-sdk": "^1.0.23",
          "crypto-browserify": "^3.12.0",
          "dotenv": "^16.4.5",
          "express": "^4.19.2",
          "os-browserify": "^0.3.0",
          "path-browserify": "^1.0.1",
          "process": "^0.11.10",
          "stream-browserify": "^3.0.0",
          "ts-loader": "^9.5.1",
          "typescript": "^5.4.5",
          "vm-browserify": "^1.1.2",
          "webpack-dev-middleware": "^7.2.1",
          "webpack-hot-middleware": "^2.26.1"
        }
      },
      {
        newWindow: true,
        openFile: 'this-is-not-a-drill-basic-example-main/src/README.md',
        showSidebar: true,
        theme: 'dark',
        view: 'default',
      },
    );    
  }  

  useEffect(() => {
    fetchExampleRepo();
  }, [temporaryAPIKeyValue.current]);

  useEffect(() => {
    if (user && user.id) {
      fetchAPIKeys(user.id);
    }
  }, [fetchAPIKeys, user]);

  useEffect(() => {
    if (playgroundAPIKeys.length > 0) {
      if (playgroundAPIKeys[0]?.expiresAt) {
        if (!pastTense(playgroundAPIKeys[0].expiresAt.toISOString())) {
          const temporaryKeyVal = playgroundAPIKeys[0].apiKey;

          const temporaryKeyExpiration = formatDisplayDate('', playgroundAPIKeys[0].expiresAt);
          console.log(`Temporary API key: ${temporaryKeyVal}`);
          temporaryAPIKeyValue.current = temporaryKeyVal; // show latest one
          setTemporaryAPIKeyExpiration(temporaryKeyExpiration);
        }
      }
    }
  }, [playgroundAPIKeys]);
  
  return (
    <Paper style={{paddingTop:'10px',marginTop:'10px'}} radius="md" p="sm">
      <Title order={2}>
        Playground Testing
      </Title>
      <Text size="md" mt="md">Experiment with our SDK in an instant <b>Stackblitz Playground</b>. Just click the green button.</Text>
      <Group>
        <Stack align="stretch" justify="flex-start">
          <div className={apiKeyClasses.apiKeyRow}>
            <Text size="md"  className={apiKeyClasses.apiTemporaryKeyDisplay}>
              {temporaryAPIKeyValue.current}
            </Text>

            <CopyButton value={temporaryAPIKeyValue.current !== null ? temporaryAPIKeyValue.current : ''} timeout={2000} >
              {({ copied, copy }) => (
                <Tooltip label={copied ? 'Copied Temporary API Key!' : 'Copy'} withArrow position="right">
                  <ActionIcon color={copied ? 'teal' : 'gray'} variant="subtle" onClick={copy}>
                    {copied ? (
                      <IconCheck style={{ width: rem(16) }} />
                    ) : (
                      <IconCopy style={{ width: rem(16) }} />
                    )}
                  </ActionIcon>
                </Tooltip>
              )}
            </CopyButton>

          </div>

          <Button onClick={gotoPlayground} disabled={repoFiles === null}
            size="sm" variant="filled" color="green" >
            {repoFiles === null ? <>Just a moment...</> : <>Jump To Playground!</>}
          </Button>
        </Stack>
        <Stack align="stretch" justify="flex-start" style={{paddingLeft:'10px', borderLeft: '1px dotted #666'}}>
        <div style={{minHeight:'120px'}}>
          { temporaryAPIKeyValue && (
              <Text fs="italic" style={{maxWidth:'100%', paddingTop:'15px'}}>
                This <b>temporary API key</b> expires at: &nbsp; <span style={{padding:'3px', border:'1px dotted #666', fontStyle:'normal', color:'green'}}>
                {temporaryAPIKeyExpiration ? temporaryAPIKeyExpiration : ''} </span> 
                <br />The API key will be automatically injected into the Playground for you and is good for one hour.
                <br />You can also watch a <Anchor target="_blank" href="https://www.loom.com/share/ffa0a90a52de4fccaacb0003fde075b4?sid=89e9d976-2f00-48d8-af01-75e56377f7d0">quick tutorial about the Playground.</Anchor>
                <br />(You can also use temporary API keys locally to try out the <Anchor target="_blank" href="https://github.com/willkessler/this-is-not-a-drill-basic-example">basic example app</Anchor>).
              </Text>
          ) }
        </div>
        </Stack>
      </Group>
      <div style={{marginTop:'10px',paddingTop:'10px', borderTop: '1px dotted #666' }}>
        <Text size="sm" fs="italic" >Here is a preview of what the Stackblitz environment will contain.</Text>
        <Anchor component="button" onClick={gotoPlayground}><Image src="/StackblitzExample.png" style={{paddingTop:'10px',width:'95%'}}/></Anchor>
      </div>
    </Paper>
  );
};


export default PlaygroundComponent;
