import React, { ReactNode } from 'react';

export enum ReactQueryAction {
  OK_AS_IS,
  REFRESH,
  INVALIDATE,
};

export type SDKProviderProps = {
  children: ReactNode;
};

export interface SDKConfig {
  apiKey: string; // required for the API, must be valid API key
  userId: string; // required for the API, autogenerated if not provided by client
  apiBaseUrl?: string;
  apiUrlString: string;
  pageId?: string;
  environments?: string;
}

export interface SDKNotification {
  uuid: string,
  createdAt: Date,
  content: string;
  pageId?: string;
  notificationType: string;
  environments: [string];
  startDate?: Date;
  endDate?: Date;
  live: boolean;
  dismissed: boolean;
  // Only stored on return values from the SDK. The notifications table in the db doesn't have user_id on it
  // but it's added in return results to allow for dynamic user_id switching.
  userId?: string;
}

export interface SDKDataReturn {
  data: SDKNotification[] | null | undefined;
  isPending: boolean;
  isError: boolean;
  error: any;
  getConfig: () => SDKConfig;
  dismiss: (notificationUuid: string) => Promise<boolean>;
  reset: () => Promise<boolean>;
  invalidate: () => void;
}
